name: Tests

on:
  pull_request:
    branches:
      - master
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3, 3.6, 3.7]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Bats
        run: sudo ./__tests__/setup-bats.sh
      - name: Install Python dependencies
        run: sudo ./__tests__/setup-pip.sh
      - name: Unit Tests
        run: sudo python3 -m unittest tests.unittests
      - name: Linter and Integration Tests
        run: sudo ./__tests__/test-ci.sh
